angular.module('myApp')
.controller("CityController", ['$scope', '$state', 'decisionfactory', function ($scope, $state, decisionfactory) {

    $scope.cities = [{ Name: "Abhayapuri - (Assam)" },
{ Name: "Achabbal - (Jammu and Kashmir)" },
{ Name: "Achalpur - (Maharashtra)" },
{ Name: "Achhnera - (Uttar Pradesh)" },
{ Name: "Adari - (Uttar Pradesh)" },
{ Name: "Adalaj - (Gujrat)" },
{ Name: "Adilabad - (Andhra Pradesh)" },
{ Name: "Adityana - (Gujrat)" },
{ Name: "pereyaapatna - (Karnataka)" },
{ Name: "Adoni - (Andhra Pradesh)" },
{ Name: "Adoor - (Kerala)" },
{ Name: "Adyar - (Karnataka)" },
{ Name: "Adra - (West Bengal)" },
{ Name: "Afzalpura - (Karnataka)" },
{ Name: "Agartala - (Tripura)" },
{ Name: "Agra - (Uttar Pradesh)" },
{ Name: "Ahiwara - (Chhattisgarh)" },
{ Name: "Ahmedabad - (Gujarat)" },
{ Name: "Ahmedgarh - (Punjab)" },
{ Name: "Ahmednagar - (Maharashtra)" },
{ Name: "Ahmedpur - (Maharashtra)" },
{ Name: "Aizawl - (Mizoram)" },
{ Name: "Ajmer - (Rajasthan)" },
{ Name: "Ajra - (Maharashtra)" },
{ Name: "Akaltara - (Chhattisgarh)" },
{ Name: "Akathiyoor - (Kerala)" },
{ Name: "Akhnoor - (Jammu and Kashmir)" },
{ Name: "Akkalkot - (Maharashtra)" },
{ Name: "Akola - (Maharashtra)" },
{ Name: "Akot - (Maharashtra)" },
{ Name: "Alandha - (Karnataka)" },
{ Name: "Alandi - (Maharashtra)" },
{ Name: "Alang - (Gujrat)" },
{ Name: "Alappuzha - (Kerala)" },
{ Name: "Aldona - (Goa)" },
{ Name: "Alibag - (Maharashtra)" },
{ Name: "Aligarh - (Uttar Pradesh)" },
{ Name: "Alipurduar - (West Bengal)" },
{ Name: "Allahabad - (Uttar Pradesh)" },
{ Name: "Almora - (Uttarakhand)" },
{ Name: "Aalanavara - (Karnataka)" },
{ Name: "Along - (Arunachal Pradesh)" },
{ Name: "Alur - (Karnataka)" },
{ Name: "Alwar - (Rajasthan)" },
{ Name: "Amadalavalasa - (Andhra Pradesh)" },
{ Name: "Amalapuram - (Andhra Pradesh)" },
{ Name: "Amalner - (Maharashtra)" },
{ Name: "Amarpur - (Bihar)" },
{ Name: "Ambad - (Maharashtra)" },
{ Name: "Ambagarh Chowki - (Chhattisgarh)" },
{ Name: "Ambaji - (Gujrat)" },
{ Name: "Ambaliyasan - (Gujrat)" },
{ Name: "Ambejogai - (Maharashtra)" },
{ Name: "Ambikaanagara - (Karnataka)" },
{ Name: "Ambikapur - (Chhattisgarh)" },
{ Name: "Ambivali Tarf Wankhal - (Maharashtra)" },
{ Name: "Amguri - (Assam)" },
{ Name: "Amini - (Lakshadweep)" },
{ Name: "Amlabad - (Jharkhand)" },
{ Name: "Amli - (Dadra and Nagar Haveli)" },
{ Name: "Amravati - (Maharashtra)" },
{ Name: "Amreli - (Gujarat)" },
{ Name: "Amritsar - (Punjab)" },
{ Name: "Amroha - (Uttar Pradesh)" },
{ Name: "Anakapalle - (Andhra Pradesh)" },
{ Name: "Anand - (Gujarat)" },
{ Name: "Anandapur - (Orissa)" },
{ Name: "Anandnagaar - (Assam)" },
{ Name: "Anantapur - (Andhra Pradesh)" },
{ Name: "Anantnag - (Jammu and Kashmir)" },
{ Name: "Ancharakandy - (Kerala)" },
{ Name: "Andada - (Gujrat)" },
{ Name: "Anekal - (Karnataka)" },
{ Name: "Ankola - (Karnataka)" },
{ Name: "Anjar - (Gujrat)" },
{ Name: "Anjangaon - (Maharashtra.Cl)" },
{ Name: "Anklav - (Gujrat)" },
{ Name: "Ankleshwar - (Gujarat)" },
{ Name: "Annigeri - (Karnataka)" },
{ Name: "Antaliya - (Gujrat)" },
{ Name: "Anugul - (Orissa)" },
{ Name: "Ara - (Jharkhand)" },
{ Name: "Arambhada - (Gujrat)" },
{ Name: "Arakkonam - (Tamil Nadu)" },
{ Name: "Araria - (Bihar)" },
{ Name: "Arang - (Chhattisgarh)" },
{ Name: "Arambagh - (West Bengal)" },
{ Name: "Arsikere - (Karnataka)" },
{ Name: "Arcot - (Tamil Nadu)" },
{ Name: "Areraj - (Bihar)" },
{ Name: "Arkalgud - (Karnataka)" },
{ Name: "Arki - (Himachal Pradesh)" },
{ Name: "Arnia - (Jammu and Kashmir)" },
{ Name: "Aroor - (Kerala)" },
{ Name: "Arrah - (Bihar)" },
{ Name: "Aruppukkottai - (Tamil Nadu)" },
{ Name: "Arvi - (Maharashtra)" },
{ Name: "Asankhurd - (Haryana)" },
{ Name: "Asansol - (West Bengal)" },
{ Name: "Asarganj - (Bihar)" },
{ Name: "Ashok Nagar - (Madhya Pradesh)" },
{ Name: "Ashta - (Maharashtra)" },
{ Name: "Ashtamichira - (Kerala)" },
{ Name: "Asika - (Orissa)" },
{ Name: "Asola - (Delhi)" },
{ Name: "Assandh - (Haryana)" },
{ Name: "Ateli - (Haryana)" },
{ Name: "Athni - (Karnataka)" },
{ Name: "Attingal - (Kerala)" },
{ Name: "Atul - (Gujrat)" },
{ Name: "Aurad - (Karnataka)" },
{ Name: "Aurangabad - (Bihar)" },
{ Name: "Aurangabad - (Maharashtra)" },
{ Name: "Ausa - (Maharashtra)" },
{ Name: "Avinissery - (Kerala)" },
{ Name: "Awantipora - (Jammu and Kashmir)" },
{ Name: "Azamgarh - (Uttar Pradesh)" },
{ Name: "Babiyal - (Haryana)" },
{ Name: "Baddi - (Himachal Pradesh)" },
{ Name: "Bade Bacheli - (Chhattisgarh)" },
{ Name: "Badaun - (Uttar Pradesh)" },
{ Name: "Badepalle - (Andhra Pradesh)" },
{ Name: "Badharghat - (Tripura)" },
{ Name: "Bagaha - (Bihar)" },
{ Name: "Bahadurgarh - (Haryana)" },
{ Name: "Bahadurganj - (Bihar)" },
{ Name: "Baharampur - (West Bengal)" },
{ Name: "Bahraich - (Uttar Pradesh)" },
{ Name: "Bairgania - (Bihar)" },
{ Name: "Bakhtiarpur - (Bihar)" },
{ Name: "Balaghat - (Madhya Pradesh)" },
{ Name: "Balangir - (Orissa)" },
{ Name: "Balasore - (Orissa)" },
{ Name: "Baleshwar - (Orissa)" },
{ Name: "Bali - (Rajasthan)" },
{ Name: "Bally - (West Bengal)" },
{ Name: "Ballabhgarh - (Haryana)" },
{ Name: "Ballia - (Uttar Pradesh)" },
{ Name: "Balod - (Chhattisgarh)" },
{ Name: "Baloda Bazar - (Chhattisgarh)" },
{ Name: "Balrampur - (Uttar Pradesh)" },
{ Name: "Balurghat - (West Bengal)" },
{ Name: "Bamra - (Orissa)" },
{ Name: "Banda - (Uttar Pradesh)" },
{ Name: "Bandikui - (Rajasthan)" },
{ Name: "Bandipore - (Jammu and Kashmir)" },
{ Name: "Banganapalle - (Andhra Pradesh)" },
{ Name: "Banka - (Bihar)" },
{ Name: "Banmankhi Bazar - (Bihar)" },
{ Name: "Banswara - (Rajasthan)" },
{ Name: "Bankura - (West Bengal)" },
{ Name: "Bapatla - (Andhra Pradesh)" },
{ Name: "Barakar - (West Bengal)" },
{ Name: "Barahiya - (Bihar)" },
{ Name: "Baramati - (Maharashtra)" },
{ Name: "Baramula - (Jammu and Kashmir)" },
{ Name: "Baran - (Rajasthan)" },
{ Name: "Barasat - (West Bengal)" },
{ Name: "Bardhaman - (West Bengal)" },
{ Name: "Barauli - (Bihar)" },
{ Name: "Barbigha - (Bihar)" },
{ Name: "Bareilly - (Uttar Pradesh)" },
{ Name: "Bargarh - (Orissa)" },
{ Name: "Barughutu - (Jharkhand)" },
{ Name: "Basna - (Chhattisgarh)" },
{ Name: "Barbil - (Orissa)" },
{ Name: "Bargarh - (Orissa)" },
{ Name: "Barh - (Bihar)" },
{ Name: "Baripada - (Orissa)" },
{ Name: "Barmer - (Rajasthan)" },
{ Name: "Barnala - (Punjab)" },
{ Name: "Barpeta - (Assam)" },
{ Name: "Barpeta Road - (Assam)" },
{ Name: "Barrackpur - (West Bengal)" },
{ Name: "Barwani - (Madhya Pradesh)" },
{ Name: "Barwala - (Haryana)" },
{ Name: "Basudebpur - (Orissa)" },
{ Name: "Batala - (Punjab)" },
{ Name: "Bathinda - (Punjab)" },
{ Name: "Bawal - (Haryana)" },
{ Name: "Bazpur - (Uttarakhand)" },
{ Name: "Beawar - (Rajasthan)" },
{ Name: "Begusarai - (Bihar)" },
{ Name: "Behea - (Bihar)" },
{ Name: "Belagaavi - (Karnataka)" },
{ Name: "Bellampalle - (Andhra Pradesh)" },
{ Name: "Ballary - (Karnataka)" },
{ Name: "Belpahar - (Orissa)" },
{ Name: "Bemetra - (Chhattisgarh)" },
{ Name: "Bengalooru - (Karnataka)" },
{ Name: "Berhampur - (Orissa)" },
{ Name: "Bethamcherla - (Andhra Pradesh)" },
{ Name: "Bettiah - (Bihar)" },
{ Name: "Betul - (Madhya Pradesh)" },
{ Name: "Bhabua - (Bihar)" },
{ Name: "Bhadrachalam - (Andhra Pradesh)" },
{ Name: "Bhadrak - (Orissa)" },
{ Name: "Bhagalpur - (Bihar)" },
{ Name: "Bhagha Purana - (Punjab)" },
{ Name: "Bhainsa - (Andhra Pradesh)" },
{ Name: "Bhajanpura - (Delhi)" },
{ Name: "Bhandara - (Maharashtra)" },
{ Name: "Bharatpur - (Rajasthan)" },
{ Name: "Bharthana - (Uttar Pradesh)" },
{ Name: "Bharuch - (Gujarat)" },
{ Name: "Bhatapara - (Chhattisgarh)" },
{ Name: "Bhavani - (Tamil Nadu)" },
{ Name: "Bhavnagar - (Gujarat)" },
{ Name: "Bhawanipatna - (Orissa)" },
{ Name: "Bheemunipatnam - (Andhra Pradesh)" },
{ Name: "Bhilai - (Chhattisgarh)" },
{ Name: "Bhilwara - (Rajasthan)" },
{ Name: "Bhimavaram - (Andhra Pradesh)" },
{ Name: "Bhinmal - (Rajasthan)" },
{ Name: "Bhiwandi - (Maharashtra)" },
{ Name: "Bhiwani - (Haryana)" },
{ Name: "Bhongir - (Andhra Pradesh)" },
{ Name: "Bhopal - (Madhya Pradesh)" },
{ Name: "Bhuban - (Orissa)" },
{ Name: "Bhubaneswar - (Orissa)" },
{ Name: "Bhuj - (Gujarat)" },
{ Name: "Bhusawal - (Maharashtra)" },
{ Name: "Bidar - (Karnataka)" },
{ Name: "Bidhan Nagar - (West Bengal)" },
{ Name: "Bihar Sharif - (Bihar)" },
{ Name: "Bijnaur - (Uttar Pradesh)" },
{ Name: "Bikaner - (Rajasthan)" },
{ Name: "Bikramganj - (Bihar)" },
{ Name: "Bilara - (Rajasthan)" },
{ Name: "Bilasipara - (Assam)" },
{ Name: "Bilaspur - (Chhattisgarh)" },
{ Name: "Bilaspur - (Himachal Pradesh)" },
{ Name: "Biramitrapur - (Orissa)" },
{ Name: "Birgaon - (Chhattisgarh)" },
{ Name: "Bobbili - (Andhra Pradesh)" },
{ Name: "Bodhan - (Andhra Pradesh)" },
{ Name: "Bodh Gaya - (Bihar)" },
{ Name: "Bokaro Steel City - (Jharkhand)" },
{ Name: "Bongaigaon - (Assam)" },
{ Name: "Bomdila - (Arunachal Pradesh)" },
{ Name: "Brahmapur - (Orissa)" },
{ Name: "Brajrajnagar - (Orissa)" },
{ Name: "Budaun - (Uttar Pradesh)" },
{ Name: "Budhlada - (Punjab)" },
{ Name: "Bulandshahr - (Uttar Pradesh)" },
{ Name: "Burhanpur - (Madhya Pradesh)" },
{ Name: "Burla - (Orissa)" },
{ Name: "Buxar - (Bihar)" },
{ Name: "Byasanagar - (Orissa)" },
{ Name: "Cambay - (Gujarat)" },
{ Name: "Chaibasa - (Jharkhand)" },
{ Name: "Chakeri - (Uttar Pradesh)" },
{ Name: "Chakradharpur - (Jharkhand)" },
{ Name: "Chalisgaon - (Maharashtra)" },
{ Name: "Chamba - (Himachal Pradesh)" },
{ Name: "Chamba - (Uttarakhand)" },
{ Name: "Champa - (Chhattisgarh)" },
{ Name: "Champawat - (Uttarakhand)" },
{ Name: "Champhai - (Mizoram)" },
{ Name: "Chamarajanagara - (Karnataka)" },
{ Name: "Chandigarh - (Punjab)" },
{ Name: "Chandil - (Jharkhand)" },
{ Name: "Chandausi - (Uttar Pradesh)" },
{ Name: "Chandrapura - (Jharkhand)" },
{ Name: "Chanpatia - (Bihar)" },
{ Name: "Charkhi Dadri - (Haryana)" },
{ Name: "Chapirevula - (Andhra Pradesh)" },
{ Name: "Chatra - (Jharkhand)" },
{ Name: "Charkhari - (Uttar Pradesh)" },
{ Name: "Chalakudy - (Kerala)" },
{ Name: "Chandrapur - (Maharashtra)" },
{ Name: "Changanassery - (Kerala)" },
{ Name: "Cheeka - (Haryana)" },
{ Name: "Chendamangalam - (Kerala)" },
{ Name: "Chengalpattu - (Tamil Nadu)" },
{ Name: "Chengannur - (Kerala)" },
{ Name: "Chennai - (Tamil Nadu)" },
{ Name: "Cherthala - (Kerala)" },
{ Name: "Cheruthazham - (Kerala)" },
{ Name: "Chhapra - (Bihar)" },
{ Name: "Chhatarpur - (Madhya Pradesh)" },
{ Name: "Chhindwara - (Madhya Pradesh)" },
{ Name: "Chikkodi - (Karnataka)" },
{ Name: "Chikkamagalur - (Karnataka)" },
{ Name: "Chilakaluripet - (Andhra Pradesh)" },
{ Name: "Chinchani - (Maharashtra)" },
{ Name: "Chinna salem - (Tamil nadu)" },
{ Name: "Chinthaamani - (Karnataka)" },
{ Name: "Chiplun - (Maharashtra)" },
{ Name: "Chirala - (Andhra Pradesh)" },
{ Name: "Chirkunda - (Jharkhand)" },
{ Name: "Chirmiri - (Chhattisgarh)" },
{ Name: "Chinsura - (West Bengal)" },
{ Name: "Chithradurga - (Karnataka)" },
{ Name: "Chittur-Thathamangalam - (Kerala)" },
{ Name: "Chitrakoot - (Madhya Pradesh)" },
{ Name: "Chittoor - (Andhra Pradesh)" },
{ Name: "Chockli - (Kerala)" },
{ Name: "Churi - (Jharkhand)" },
{ Name: "Churu - (Rajasthan)" },
{ Name: "Coimbatore - (Tamil Nadu)" },
{ Name: "Colgong - (Bihar)" },
{ Name: "Contai - (West Bengal)" },
{ Name: "Cooch Behar - (West Bengal)" },
{ Name: "Coonoor - (Tamil Nadu)" },
{ Name: "Cuddalore - (Tamil Nadu)" },
{ Name: "Cuddapah - (Andhra Pradesh)" },
{ Name: "Curchorem Cacora - (Goa)" },
{ Name: "Cuttack - (Orissa)" },
{ Name: "Chikkaballapura - (Karnataka)" },
{ Name: "Chandan Bara - (Bihar)" },
{ Name: "Dabra - (Madhya Pradesh)" },
{ Name: "Dadri - (Uttar Pradesh)" },
{ Name: "Dahod - (Gujarat)" },
{ Name: "Dalhousie - (Himachal Pradesh)" },
{ Name: "Dalkhola - (West Bengal)" },
{ Name: "Dalli-Rajhara - (Chhattisgarh)" },
{ Name: "Dalsinghsarai - (Bihar)" },
{ Name: "Daltonganj - (Jharkhand)" },
{ Name: "Daman and Diu - (Daman and Diu)" },
{ Name: "Damoh - (Madhya Pradesh)" },
{ Name: "Darbhanga - (Bihar)" },
{ Name: "Darjeeling - (West Bengal)" },
{ Name: "Dasua - (Punjab)" },
{ Name: "Datia - (Madhya Pradesh)" },
{ Name: "Daudnagar - (Bihar)" },
{ Name: "Daund - (Maharashtra)" },
{ Name: "Davanageray - (Karnataka)" },
{ Name: "Debagarh - (Orissa)" },
{ Name: "Deesa - (Gujarat)" },
{ Name: "Dehgam - (Gujarat)" },
{ Name: "Dehradun - (Uttarakhand)" },
{ Name: "Dehri-on-Sone - (Bihar)" },
{ Name: "Deoghar - (Jharkhand)" },
{ Name: "Deoria - (Uttar Pradesh)" },
{ Name: "Devarakonda - (Andhra Pradesh)" },
{ Name: "Devgarh - (Maharashtra)" },
{ Name: "Devgarh - (Rajasthan)" },
{ Name: "Dewas - (Madhya Pradesh)" },
{ Name: "Dhaka - (Bihar)" },
{ Name: "Dhamtari - (Chhattisgarh)" },
{ Name: "Dhanbad - (Jharkhand)" },
{ Name: "Dhar - (Madhya Pradesh)" },
{ Name: "Dharampur - (Gujarat)" },
{ Name: "Dharamsala - (Himachal Pradesh)" },
{ Name: "Dharmanagar - (Tripura)" },
{ Name: "Dharmapuri - (Tamil Nadu)" },
{ Name: "Dharmavaram - (Andhra Pradesh)" },
{ Name: "Dharwad - (Karnataka)" },
{ Name: "Dhekiajuli - (Assam)" },
{ Name: "Dhenkanal - (Orissa)" },
{ Name: "Dholka - (Gujarat)" },
{ Name: "Dhubri - (Assam)" },
{ Name: "Dhule - (Maharashtra)" },
{ Name: "Dhulian - (West Bengal)" },
{ Name: "Dhuri - (Punjab)" },
{ Name: "Dibrugarh - (Assam)" },
{ Name: "Digboi - (Assam)" },
{ Name: "Dighwara - (Bihar)" },
{ Name: "Dimapur - (Nagaland)" },
{ Name: "Dinanagar - (Punjab)" },
{ Name: "Dindigul - (Tamil Nadu)" },
{ Name: "Diphu - (Assam)" },
{ Name: "Dipka - (Chhattisgarh)" },
{ Name: "Dispur - (Assam)" },
{ Name: "Dombivli - (Maharashtra)" },
{ Name: "Dongargarh - (Chhattisgarh)" },
{ Name: "Duliajan Oil Town - (Assam)" },
{ Name: "Dumdum - (West Bengal)" },
{ Name: "Dumka - (Jharkhand)" },
{ Name: "Dumraon - (Bihar)" },
{ Name: "Durg-Bhilai Nagar - (Chhattisgarh)" },
{ Name: "Durgapur - (Maharashtra)" },
{ Name: "Durgapur - (West Bengal)" },
{ Name: "Dwarka - (Gujarat)" },
{ Name: "Ellenabad - (Haryana)" },
{ Name: "Eluru - (Andhra Pradesh)" },
{ Name: "Erattupetta - (Kerala)" },
{ Name: "Erode - (Tamil Nadu)" },
{ Name: "Etah - (Uttar Pradesh)" },
{ Name: "Etawah - (Uttar Pradesh)" },
{ Name: "Faizabad - (Uttar Pradesh)" },
{ Name: "Falna - (Rajasthan)" },
{ Name: "Faridabad - (Haryana)" },
{ Name: "Faridkot - (Punjab)" },
{ Name: "Farooqnagar - (Andhra Pradesh)" },
{ Name: "Farrukhabad - (Uttar Pradesh)" },
{ Name: "Fatehabad - (Haryana)" },
{ Name: "Fatehabad - (Madhya Pradesh)" },
{ Name: "Fatehabad - (Uttar Pradesh)" },
{ Name: "Fatehgarh - (Uttar Pradesh)" },
{ Name: "Fatehpur Chaurasi - (Uttar Pradesh)" },
{ Name: "Fatehpur Sikri - (Uttar Pradesh)" },
{ Name: "Fatehpur - (Rajasthan)" },
{ Name: "Fatehpur - (Uttar Pradesh)" },
{ Name: "Fatehpur - (Uttar Pradesh)" },
{ Name: "Fatwah - (Bihar)" },
{ Name: "Fazilka - (Punjab)" },
{ Name: "Forbesganj - (Bihar)" },
{ Name: "Firozabad - (Uttar Pradesh)" },
{ Name: "Firozpur - (Punjab)" },
{ Name: "Firozpur Cantt. - (Punjab)" },
{ Name: "Gadhaga - (Karnataka)" },
{ Name: "Gadchiroli - (Maharashtra)" },
{ Name: "Gadwal - (Andhra Pradesh)" },
{ Name: "Ganaur - (Haryana)" },
{ Name: "Gandhidham - (Gujarat)" },
{ Name: "Gandhinagar - (Gujarat)" },
{ Name: "Gangtok - (Sikkim)" },
{ Name: "Ganjam - (Orissa)" },
{ Name: "Garhwa - (Jharkhand)" },
{ Name: "Gauripur - (Assam)" },
{ Name: "Gaya - (Bihar)" },
{ Name: "Gharaunda - (Haryana)" },
{ Name: "Ghatampur - (Uttar Pradesh)" },
{ Name: "Ghatanji - (Maharashtra)" },
{ Name: "Ghatshila - (Jharkhand)" },
{ Name: "Ghaziabad - (Uttar Pradesh)" },
{ Name: "Ghazipur - (Uttar Pradesh)" },
{ Name: "Giddarbaha - (Punjab)" },
{ Name: "Giridih - (Jharkhand)" },
{ Name: "Goa Velha - (Goa)" },
{ Name: "Goalpara - (Assam)" },
{ Name: "Gobindgarh - (Punjab)" },
{ Name: "Gobranawapara - (Chhattisgarh)" },
{ Name: "Godda - (Jharkhand)" },
{ Name: "Godhra - (Gujarat)" },
{ Name: "Gogri Jamalpur - (Bihar)" },
{ Name: "Gohana - (Haryana)" },
{ Name: "Gokak - (Karnataka)" },
{ Name: "Golaghat - (Assam)" },
{ Name: "Gomoh - (Jharkhand)" },
{ Name: "Gondiya - (Maharashtra)" },
{ Name: "Gooty - (Andhra Pradesh)" },
{ Name: "Gopalganj - (Bihar)" },
{ Name: "Gorakhpur - (Uttar Pradesh)" },
{ Name: "Greater Noida - (Uttar Pradesh)" },
{ Name: "Gudalur - (Tamil Nadu)" },
{ Name: "Gudalur - (Tamil Nadu)" },
{ Name: "Gudalur - (Tamil Nadu)" },
{ Name: "Gudivada - (Andhra Pradesh)" },
{ Name: "Gudur - (Andhra Pradesh)" },
{ Name: "Gulbarga - (Karnataka)" },
{ Name: "Gumia - (Jharkhand)" },
{ Name: "Gumla - (Jharkhand)" },
{ Name: "Guna - (Madhya Pradesh)" },
{ Name: "Gundlupet - (Karnataka)" },
{ Name: "Guntakal - (Andhra Pradesh)" },
{ Name: "Guntur - (Andhra Pradesh)" },
{ Name: "Gunupur - (Orissa)" },
{ Name: "Gurdaspur - (Punjab)" },
{ Name: "Gurgaon - (Haryana)" },
{ Name: "Guruvayoor - (Kerala)" },
{ Name: "Guwahati - (Assam)" },
{ Name: "Gwalior - (Madhya pradesh)" },
{ Name: "Haflong - (Assam)" },
{ Name: "Hailakandi - (Assam)" },
{ Name: "Hajipur - (Bihar)" },
{ Name: "Haldia - (West Bengal)" },
{ Name: "Haldwani - (Uttarakhand)" },
{ Name: "Haibat(Yamuna Nagar) - (Haryana)" },
{ Name: "Hamirpur - (Himachal Pradesh)" },
{ Name: "Hamirpur - (Uttar Pradesh)" },
{ Name: "Hansi - (Haryana)" },
{ Name: "Hanuman Junction - (Andhra Pradesh)" },
{ Name: "Hanumangarh - (Rajasthan)" },
{ Name: "Harda - (Madhya Pradesh)" },
{ Name: "Hardoi - (Uttar Pradesh)" },
{ Name: "Haridwar - (Uttarakhand)" },
{ Name: "Harsawa - (Rajasthan)" },
{ Name: "Haasana - (Karnataka)" },
{ Name: "Hastinapur - (Uttar Pradesh)" },
{ Name: "Hathras - (Uttar Pradesh)" },
{ Name: "Hazaribag - (Jharkhand)" },
{ Name: "Hilsa - (Bihar)" },
{ Name: "Himatnagar - (Gujarat)" },
{ Name: "Hindupur - (Andhra Pradesh)" },
{ Name: "Hinjilicut - (Orissa)" },
{ Name: "Hisar - (Haryana)" },
{ Name: "Hisua - (Bihar)" },
{ Name: "Hodal - (Haryana)" },
{ Name: "Hojai - (Assam)" },
{ Name: "Hoshiarpur - (Punjab)" },
{ Name: "Hosapet - (Karnataka)" },
{ Name: "Howrah - (West Bengal)" },
{ Name: "Hubbali - (Karnataka)" },
{ Name: "Hugli-Chuchura - (West Bengal)" },
{ Name: "Hussainabad - (Jharkhand)" },
{ Name: "Hyderabad - (Andhra Pradesh)" },
{ Name: "Ichalkaranji - (Maharashtra)" },
{ Name: "Ichchapuram - (Andhra Pradesh)" },
{ Name: "Idar - (Gujarat)" },
{ Name: "Imphal - (Manipur)" },
{ Name: "Indore - (Madhya Pradesh)" },
{ Name: "Indranagar - (Tripura)" },
{ Name: "Irinjalakuda - (Kerala)" },
{ Name: "Islampur - (Bihar)" },
{ Name: "Islampur - (West Bengal)" },
{ Name: "Itanagar - (Arunachal Pradesh)" },
{ Name: "Itarsi - (Madhya Pradesh)" },
{ Name: "Jabalpur - (Madhya Pradesh)" },
{ Name: "Jagadhri - (Haryana)" },
{ Name: "Jagatsinghapur - (Orissa)" },
{ Name: "Jagdalpur - (Chhattisgarh)" },
{ Name: "Jagdispur - (Bihar)" },
{ Name: "Jaggaiahpet - (Andhra Pradesh)" },
{ Name: "Jagraon - (Punjab)" },
{ Name: "Jagtial - (Andhra Pradesh)" },
{ Name: "Jaipur - (Rajasthan)" },
{ Name: "Jais - (Uttar Pradesh)" },
{ Name: "Jaisalmer - (Rajasthan)" },
{ Name: "Jaitaran - (Rajasthan)" },
{ Name: "Jaitu - (Punjab)" },
{ Name: "Jajapur - (Orissa)" },
{ Name: "Jajmau - (Uttar Pradesh)" },
{ Name: "Jalalabad - (Punjab)" },
{ Name: "Jalna - (Maharashtra)" },
{ Name: "Jalandhar Cantt. - (Punjab)" },
{ Name: "Jalandhar - (Punjab)" },
{ Name: "Jaleswar - (Orissa)" },
{ Name: "Jalgaon - (Maharashtra)" },
{ Name: "Jalore - (Rajasthan)" },
{ Name: "Jamalpur - (Bihar)" },
{ Name: "Jammalamadugu - (Andhra Pradesh)" },
{ Name: "Jammu - (Jammu and Kashmir)" },
{ Name: "Jamnagar - (Gujarat)" },
{ Name: "Jamshedpur - (Jharkhand)" },
{ Name: "Jamtara - (Jharkhand)" },
{ Name: "Jamui - (Bihar)" },
{ Name: "Jandiala - (Punjab)" },
{ Name: "Jangaon - (Andhra Pradesh)" },
{ Name: "Janjgir - (Chhattisgarh)" },
{ Name: "Jashpurnagar - (Chhattisgarh)" },
{ Name: "Jaspur - (Uttarakhand)" },
{ Name: "Jatani - (Orissa)" },
{ Name: "Jaunpur - (Uttar Pradesh)" },
{ Name: "Jehanabad - (Bihar)" },
{ Name: "Jeypur - (Orissa)" },
{ Name: "Jhabua - (Madhya Pradesh)" },
{ Name: "Jhajha - (Bihar)" },
{ Name: "Jhajjar - (Haryana)" },
{ Name: "Jhalawar - (Rajasthan)" },
{ Name: "Jhanjharpur - (Bihar)" },
{ Name: "Jhansi - (Uttar Pradesh)" },
{ Name: "Jhargram - (West Bengal)" },
{ Name: "Jharsuguda - (Orissa)" },
{ Name: "Jhumri Tilaiya - (Jharkhand)" },
{ Name: "Jhunjhunu - (Rajasthan)" },
{ Name: "Jind - (Haryana)" },
{ Name: "Joda - (Orissa)" },
{ Name: "Jodhpur - (Rajasthan)" },
{ Name: "Jogabani - (Bihar)" },
{ Name: "Jogendranagar - (Tripura)" },
{ Name: "Jorhat - (Assam)" },
{ Name: "Jowai - (Meghalaya)" },
{ Name: "Junagadh - (Gujarat)" },
{ Name: "Junnar - (Maharashtra)" },
{ Name: "Kadapa - (Andhra Pradesh)" },
{ Name: "Kadi - (Gujarat)" },
{ Name: "Kadiri - (Andhra Pradesh)" },
{ Name: "Kadirur - (Kerala)" },
{ Name: "Kagaznagar - (Andhra Pradesh)" },
{ Name: "Kailaras - (Madhya Pradesh)" },
{ Name: "Kailasahar - (Tripura)" },
{ Name: "Kaithal - (Haryana)" },
{ Name: "Kakching - (Manipur)" },
{ Name: "Kakinada - (Andhra Pradesh)" },
{ Name: "Kalan Wali - (Haryana)" },
{ Name: "Kalavad - (Gujarat)" },
{ Name: "Kalburgi - (Karnataka)" },
{ Name: "Kalimpong - (West Bengal)" },
{ Name: "Kalka - (Haryana)" },
{ Name: "Kalliasseri - (Kerala)" },
{ Name: "Kalpi - (Uttar Pradesh)" },
{ Name: "Kalol - (Gujarat)" },
{ Name: "Kalpetta - (Kerala)" },
{ Name: "Kalyan - (Maharashtra)" },
{ Name: "Kalyandurg - (Andhra Pradesh)" },
{ Name: "Kamareddy - (Andhra Pradesh)" },
{ Name: "Kamthi - (Maharashtra)" },
{ Name: "Kanchipuram - (Tamil Nadu)" },
{ Name: "Kandukur - (Andhra Pradesh)" },
{ Name: "Kanhangad - (Kerala)" },
{ Name: "Kanjikkuzhi - (Kerala)" },
{ Name: "Kanker - (Chhattisgarh)" },
{ Name: "Kannur - (Kerala)" },
{ Name: "Kanpur - (Uttar Pradesh)" },
{ Name: "Kantabanji - (Orissa)" },
{ Name: "Kanti - (Bihar)" },
{ Name: "Kapadvanj - (Gujarat)" },
{ Name: "Kapurthala - (Punjab)" },
{ Name: "Karad - (Maharashtra)" },
{ Name: "Karaikal - (Pondicherry)" },
{ Name: "Karaikudi - (Tamil Nadu)" },
{ Name: "Karanjia - (Orissa)" },
{ Name: "Karimganj - (Assam)" },
{ Name: "Karimnagar - (Andhra Pradesh)" },
{ Name: "Karjan - (Gujarat)" },
{ Name: "karjat - (maharashtra)" },
{ Name: "Kaarkala - (Karnataka)" },
{ Name: "Karnal - (Haryana)" },
{ Name: "Karoran - (Punjab)" },
{ Name: "Kartarpur - (Punjab)" },
{ Name: "Karur - (Tamil Nadu)" },
{ Name: "Karungal - (Tamil Nadu)" },
{ Name: "Kaarawaara - (Karnataka)" },
{ Name: "Kasaragod - (Kerala)" },
{ Name: "Kashipur - (Uttarakhand)" },
{ Name: "Kathua - (Jammu and Kashmir)" },
{ Name: "Katihar - (Bihar)" },
{ Name: "Katni - (Madhya Pradesh)" },
{ Name: "Kavali - (Andhra Pradesh)" },
{ Name: "Kavaratti - (Lakshadweep)" },
{ Name: "Kawardha - (Chhattisgarh)" },
{ Name: "Kayamkulam - (Kerala)" },
{ Name: "Kendrapara - (Orissa)" },
{ Name: "Kendujhar - (Orissa)" },
{ Name: "Keshod - (Gujarat)" },
{ Name: "Keylong - (Himachal Pradesh)" },
{ Name: "Khagaria - (Bihar)" },
{ Name: "Khambhalia - (Gujarat)" },
{ Name: "Khambhat - (Gujarat)" },
{ Name: "Khammam - (Andhra Pradesh)" },
{ Name: "Khanna - (Punjab)" },
{ Name: "Kharagpur - (Bihar)" },
{ Name: "Kharagpur - (West Bengal)" },
{ Name: "Kharar - (Punjab)" },
{ Name: "Kheda - (Gujarat)" },
{ Name: "Khedbrahma - (Gujarat)" },
{ Name: "Kheralu - (Gujarat)" },
{ Name: "Kheri - (Uttar Pradesh)" },
{ Name: "Khordha - (Orissa)" },
{ Name: "Khowai - (Tripura)" },
{ Name: "Khunti - (Jharkhand)" },
{ Name: "Khurai - (Madhya Pradesh)" },
{ Name: "kichha - (Uttarakhand)" },
{ Name: "Kishanganj - (Bihar)" },
{ Name: "Kochi - (Kerala)" },
{ Name: "Kodad - (Andhra Pradesh)" },
{ Name: "Kodinar - (Gujarat)" },
{ Name: "Kodungallur - (Kerala)" },
{ Name: "Kohima - (Nagaland)" },
{ Name: "Kokrajhar - (Assam)" },
{ Name: "Kolaara - (Karnataka)" },
{ Name: "Kolhapur - (Maharashtra)" },
{ Name: "Kolkata - (West Bengal)" },
{ Name: "Kollam - (Kerala)" },
{ Name: "Kollankodu - (Tamil Nadu)" },
{ Name: "Kondagaon - (Chhattisgarh)" },
{ Name: "Konnagar - (West Bengal)" },
{ Name: "Koothuparamba - (Kerala)" },
{ Name: "Koraput - (Orissa)" },
{ Name: "Korba - (Chhattisgarh)" },
{ Name: "Koratla - (Andhra Pradesh)" },
{ Name: "Kot Kapura - (Punjab)" },
{ Name: "Kota - (Karnataka)" },
{ Name: "Kota - (Rajasthan)" },
{ Name: "Kota - (Uttar Pradesh)" },
{ Name: "Kotdwara - (Uttarakhand)" },
{ Name: "Kothagudem - (Andhra Pradesh)" },
{ Name: "Kothamangalam - (Kerala)" },
{ Name: "Kothapeta - (Andhra Pradesh)" },
{ Name: "Kotma - (Madhya Pradesh)" },
{ Name: "Kottayam - (Kerala)" },
{ Name: "Kovvur - (Andhra Pradesh)" },
{ Name: "Kozhikode - (Kerala)" },
{ Name: "Krishnanagar - (West Bengal)" },
{ Name: "Kuchinda - (Orissa)" },
{ Name: "Kunnamkulam - (Kerala)" },
{ Name: "Kurali - (Punjab)" },
{ Name: "Kurnool - (Andhra Pradesh)" },
{ Name: "Kyathampalle - (Andhra Pradesh)" },
{ Name: "Lachhmangarh - (Rajasthan)" },
{ Name: "Ladnu - (Rajasthan)" },
{ Name: "Ladwa - (Haryana)" },
{ Name: "Lahar - (Madhya Pradesh)" },
{ Name: "Laharpur - (Uttar Pradesh)" },
{ Name: "Lakheri - (Rajasthan)" },
{ Name: "Lakhimpur - (Uttar Pradesh)" },
{ Name: "Lakhisarai - (Bihar)" },
{ Name: "Lakshmishawara - (Karnataka)" },
{ Name: "Lal Gopalganj Nindaura - (Uttar Pradesh)" },
{ Name: "Lalganj - (Bihar)" },
{ Name: "Lalgudi - (Tamil Nadu)" },
{ Name: "Lalitpur - (Uttar Pradesh)" },
{ Name: "Lalganj - (Uttar Pradesh)" },
{ Name: "Lalsot - (Rajasthan)" },
{ Name: "Lanka - (Assam)" },
{ Name: "Lar - (Uttar Pradesh)" },
{ Name: "Lathi - (Gujarat)" },
{ Name: "Latur - (Maharashtra)" },
{ Name: "Leh - (Jammu and Kashmir)" },
{ Name: "Lilong - (Manipur)" },
{ Name: "Limbdi - (Gujarat)" },
{ Name: "Lingsuguru - (Karnataka)" },
{ Name: "Loha - (Maharashtra)" },
{ Name: "Lohardaga - (Jharkhand)" },
{ Name: "Lonar - (Maharashtra)" },
{ Name: "Lonavla - (Maharashtra)" },
{ Name: "Longowal - (Punjab)" },
{ Name: "Loni - (Uttar Pradesh)" },
{ Name: "Losal - (Rajasthan)" },
{ Name: "Lucknow - (Uttar Pradesh)" },
{ Name: "Ludhiana - (Punjab)" },
{ Name: "Lumding - (Assam)" },
{ Name: "Lunawada - (Gujarat)" },
{ Name: "Lundi - (Madhya Pradesh)" },
{ Name: "Lunglei - (Mizoram)" },
{ Name: "Macherla - (Andhra Pradesh)" },
{ Name: "Machilipatnam - (Andhra Pradesh)" },
{ Name: "Madanapalle - (Andhra Pradesh)" },
{ Name: "Maddhuru - (Karnataka)" },
{ Name: "Madgaon - (Goa)" },
{ Name: "Madhepura - (Bihar)" },
{ Name: "Madhubani - (Bihar)" },
{ Name: "Madhugiri - (Karnataka)" },
{ Name: "Madhupur - (Jharkhand)" },
{ Name: "Madhyamgram - (Orissa)" },
{ Name: "Madikeri - (Karnataka)" },
{ Name: "Madurai - (Tamil Nadu)" },
{ Name: "Maagadi - (Karnataka)" },
{ Name: "Mahabaleswar - (Maharashtra)" },
{ Name: "Mahad - (Maharashtra)" },
{ Name: "Mahbubnagar - (Andhra Pradesh)" },
{ Name: "Mahalingapura - (Karnataka)" },
{ Name: "Maharajganj - (Bihar)" },
{ Name: "Maharajpur - (Madhya Pradesh)" },
{ Name: "Mahasamund - (Chhattisgarh)" },
{ Name: "Mahe - (Pondicherry)" },
{ Name: "Mahendragarh - (Chhattisgarh)" },
{ Name: "Mahendragarh - (Haryana)" },
{ Name: "Mahesana - (Gujarat)" },
{ Name: "Mahidpur - (Madhya Pradesh)" },
{ Name: "Mahnar Bazar - (Bihar)" },
{ Name: "Mahoba - (Uttar Pradesh)" },
{ Name: "Mahuli - (Maharashtra)" },
{ Name: "Mahuva - (Gujarat)" },
{ Name: "Mahwa - (Rajasthan)" },
{ Name: "Maihar - (Madhya Pradesh)" },
{ Name: "Mainaguri - (West Bengal)" },
{ Name: "Makhdumpur - (Bihar)" },
{ Name: "Makrana - (Rajasthan)" },
{ Name: "Mal - (West Bengal)" },
{ Name: "Malajkhand - (Madhya Pradesh)" },
{ Name: "Malappuram - (Kerala)" },
{ Name: "Malavalli - (Karnataka)" },
{ Name: "Malegaon - (Maharashtra)" },
{ Name: "Malerkotla - (Punjab)" },
{ Name: "Malkangiri - (Orissa)" },
{ Name: "Malkapur - (Maharashtra)" },
{ Name: "Malout - (Punjab)" },
{ Name: "Malpura - (Rajasthan)" },
{ Name: "Maaluru - (Karnataka)" },
{ Name: "Manasa - (Madhya Pradesh)" },
{ Name: "Manavadar - (Gujarat)" },
{ Name: "Manawar - (Madhya Pradesh)" },
{ Name: "Manchar - (Maharashtra)" },
{ Name: "Mancherial - (Andhra Pradesh)" },
{ Name: "Mandalgarh - (Rajasthan)" },
{ Name: "Mandamarri - (Andhra Pradesh)" },
{ Name: "Mandapeta - (Andhra Pradesh)" },
{ Name: "Mandawa - (Rajasthan)" },
{ Name: "Mandi - (Himachal Pradesh)" },
{ Name: "Mandi Dabwali - (Haryana)" },
{ Name: "Mandideep - (Madhya Pradesh)" },
{ Name: "Mandla - (Madhya Pradesh)" },
{ Name: "Mandsaur - (Madhya Pradesh)" },
{ Name: "Mandvi - (Gujarat)" },
{ Name: "Mandya - (Karnataka)" },
{ Name: "Maner - (Bihar)" },
{ Name: "Manesar - (Haryana)" },
{ Name: "Mangalagiri - (Andhra Pradesh)" },
{ Name: "Mangaldoi - (Assam)" },
{ Name: "Mangalooru - (Karnataka)" },
{ Name: "Mangalvedhe - (Maharashtra)" },
{ Name: "Manglaur - (Uttarakhand)" },
{ Name: "Mangrol - (Gujarat)" },
{ Name: "Mangrol - (Rajasthan)" },
{ Name: "Mangrulpir - (Maharashtra)" },
{ Name: "Manihari - (Bihar)" },
{ Name: "Manjlegaon - (Maharashtra)" },
{ Name: "Mankachar - (Assam)" },
{ Name: "Manmad - (Maharashtra)" },
{ Name: "Mansa - (Punjab)" },
{ Name: "Mansa - (Gujarat)" },
{ Name: "Manuguru - (Andhra Pradesh)" },
{ Name: "Maanvi - (Karnataka)" },
{ Name: "Manwath - (Maharashtra)" },
{ Name: "Mapusa - (Goa)" },
{ Name: "Margao - (Goa)" },
{ Name: "Margherita - (Assam)" },
{ Name: "Marhaura - (Bihar)" },
{ Name: "Mariani - (Assam)" },
{ Name: "Marigaon - (Assam)" },
{ Name: "Markapur - (Andhra Pradesh)" },
{ Name: "Marmagao - (Goa)" },
{ Name: "Masaurhi - (Bihar)" },
{ Name: "Mathabhanga - (West Bengal)" },
{ Name: "Mathura - (Uttar Pradesh)" },
{ Name: "Mattannur - (Kerala)" },
{ Name: "Mauganj - (Madhya Pradesh)" },
{ Name: "Maur - (Punjab)" },
{ Name: "Mavelikkara - (Kerala)" },
{ Name: "Mavoor - (Kerala)" },
{ Name: "Mayang Imphal - (Manipur)" },
{ Name: "Medak - (Andhra Pradesh)" },
{ Name: "Medinipur - (West Bengal)" },
{ Name: "Meerut - (Uttar Pradesh)" },
{ Name: "Mehkar - (Maharashtra)" },
{ Name: "Mehmedabad - (Gujarat)" },
{ Name: "Memari - (West Bengal)" },
{ Name: "Merta City - (Rajasthan)" },
{ Name: "Mhaswad - (Maharashtra)" },
{ Name: "Mhow Cantonment - (Madhya Pradesh)" },
{ Name: "Mhowgaon - (Madhya Pradesh)" },
{ Name: "Mihijam - (Jharkhand)" },
{ Name: "Mira-Bhayandar - (Maharashtra)" },
{ Name: "Miraj - (Maharashtra)" },
{ Name: "Mirganj - (Bihar)" },
{ Name: "Miryalaguda - (Andhra Pradesh)" },
{ Name: "Mirzapur - (Uttar Pradesh)" },
{ Name: "Mithapur - (Gujarat)" },
{ Name: "Modasa - (Gujarat)" },
{ Name: "Modinagar - (Uttar Pradesh)" },
{ Name: "Moga - (Punjab)" },
{ Name: "Mogalthur - (Andhra Pradesh)" },
{ Name: "Mohali - (Punjab)" },
{ Name: "Mohania - (Bihar)" },
{ Name: "Mokama - (Bihar)" },
{ Name: "Mokameh - (Bihar)" },
{ Name: "Mokokchung - (Nagaland)" },
{ Name: "Monoharpur - (West Bengal)" },
{ Name: "Moradabad - (Uttar Pradesh)" },
{ Name: "Morena - (Madhya Pradesh)" },
{ Name: "Morinda - (Punjab)" },
{ Name: "Morshi - (Maharashtra)" },
{ Name: "Morvi - (Gujarat)" },
{ Name: "Motihari - (Bihar)" },
{ Name: "Motipur - (Bihar)" },
{ Name: "Mount Abu - (Rajasthan)" },
{ Name: "Mudalagi - (Karnataka)" },
{ Name: "Mudabidri - (Karnataka)" },
{ Name: "Muddebihala - (Karnataka)" },
{ Name: "Mudhola - (Karnataka)" },
{ Name: "Mukatsar - (Punjab)" },
{ Name: "Mukerian - (Punjab)" },
{ Name: "Mukhed - (Maharashtra)" },
{ Name: "Muktsar - (Punjab)" },
{ Name: "Mul - (Maharashtra)" },
{ Name: "Mulabaagilu - (Karnataka)" },
{ Name: "Multai - (Madhya Pradesh)" },
{ Name: "Mumbai - (Maharashtra)" },
{ Name: "Mundaragi - (Karnataka)" },
{ Name: "Mungeli - (Chhattisgarh)" },
{ Name: "Munger - (Bihar)" },
{ Name: "Muradnagar - (Uttar Pradesh)" },
{ Name: "Murliganj - (Bihar)" },
{ Name: "Murshidabad - (West Bengal)" },
{ Name: "Murtijapur - (Maharashtra)" },
{ Name: "Murwara - (Madhya Pradesh)" },
{ Name: "Musabani - (Jharkhand)" },
{ Name: "Mussoorie - (Uttarakhand)" },
{ Name: "Muvattupuzha - (Kerala)" },
{ Name: "Muzaffarnagar - (Uttar Pradesh)" },
{ Name: "Muzaffarpur - (Bihar)" },
{ Name: "Mysooru - (Karnataka)" },
{ Name: "Nabadwip - (West Bengal)" },
{ Name: "Nabarangapur - (Orissa)" },
{ Name: "Nabha - (Punjab)" },
{ Name: "Nadbai - (Rajasthan)" },
{ Name: "Nadiad - (Gujarat)" },
{ Name: "Nagaon - (Assam)" },
{ Name: "Nagapattinam - (Tamil Nadu)" },
{ Name: "Nagar - (Rajasthan)" },
{ Name: "Nagari - (Andhra Pradesh)" },
{ Name: "Nagarkurnool - (Andhra Pradesh)" },
{ Name: "Nagaur - (Rajasthan)" },
{ Name: "Nagda - (Madhya Pradesh)" },
{ Name: "Nagercoil - (Tamil Nadu)" },
{ Name: "Nagina - (Uttar Pradesh)" },
{ Name: "Nagla - (Uttarakhand)" },
{ Name: "Nagpur - (Maharashtra)" },
{ Name: "Nahan - (Himachal Pradesh)" },
{ Name: "Naharlagun - (Arunachal Pradesh)" },
{ Name: "Naihati - (West Bengal)" },
{ Name: "Naila Janjgir - (Chhattisgarh)" },
{ Name: "Nainital - (Uttarakhand)" },
{ Name: "Nainpur - (Madhya Pradesh)" },
{ Name: "Najibabad - (Uttar Pradesh)" },
{ Name: "Nakodar - (Punjab)" },
{ Name: "Nakur - (Uttar Pradesh)" },
{ Name: "Nalasopara - (Maharashtra)" },
{ Name: "Nalbari - (Assam)" },
{ Name: "Namagiripettai - (Tamil Nadu)" },
{ Name: "Namakkal - (Tamil Nadu)" },
{ Name: "Nanded-Waghala - (Maharashtra)" },
{ Name: "Nandgaon - (Maharashtra)" },
{ Name: "Nandivaram-Guduvancheri - (Tamil Nadu)" },
{ Name: "Nandura - (Maharashtra)" },
{ Name: "Nandurbar - (Maharashtra)" },
{ Name: "Nandyal - (Andhra Pradesh)" },
{ Name: "Nangal - (Punjab)" },
{ Name: "Nanjanagoodu - (Karnataka)" },
{ Name: "Nanjikottai - (Tamil Nadu)" },
{ Name: "Nanpara - (Uttar Pradesh)" },
{ Name: "Narasapur - (Andhra Pradesh)" },
{ Name: "Narasaraopet - (Andhra Pradesh)" },
{ Name: "Naraura - (Uttar Pradesh)" },
{ Name: "Narayanpet - (Andhra Pradesh)" },
{ Name: "Nargund - (Rajasthan)" },
{ Name: "Narkatiaganj - (Bihar)" },
{ Name: "Narkhed - (Maharashtra)" },
{ Name: "Narnaul - (Haryana)" },
{ Name: "Narsinghgarh - (Madhya Pradesh)" },
{ Name: "Narsinghgarh - (Madhya Pradesh)" },
{ Name: "Narsipatnam - (Andhra Pradesh)" },
{ Name: "Narwana - (Haryana)" },
{ Name: "Nashik - (Maharashtra)" },
{ Name: "Nasirabad - (Rajasthan)" },
{ Name: "Natham - (Tamil Nadu)" },
{ Name: "Nathdwara - (Rajasthan)" },
{ Name: "Naugachhia - (Bihar)" },
{ Name: "Naugawan Sadat - (Uttar Pradesh)" },
{ Name: "Nautanwa - (Uttar Pradesh)" },
{ Name: "Navalgund - (Rajasthan)" },
{ Name: "Navi Mumbai - (Maharashtra)" },
{ Name: "Navsari - (Gujarat)" },
{ Name: "Nawabganj - (Uttar Pradesh)" },
{ Name: "Nawada - (Bihar)" },
{ Name: "Nawalgarh - (Rajasthan)" },
{ Name: "Nawanshahr - (Punjab)" },
{ Name: "Nawapur - (Maharashtra)" },
{ Name: "Nedumangad - (Kerala)" },
{ Name: "Neem-Ka-Thana - (Rajasthan)" },
{ Name: "Neemuch - (Madhya Pradesh)" },
{ Name: "Nehtaur - (Uttar Pradesh)" },
{ Name: "Nelamangala - (Rajasthan)" },
{ Name: "Nellikuppam - (Tamil Nadu)" },
{ Name: "Nellore - (Andhra Pradesh)" },
{ Name: "Nepanagar - (Madhya Pradesh)" },
{ Name: "New Delhi - (Delhi)" },
{ Name: "Neyveli - (Tamil Nadu)" },
{ Name: "Neyyattinkara - (Kerala)" },
{ Name: "Nidadavole - (Andhra Pradesh)" },
{ Name: "Nilanga - (Maharashtra)" },
{ Name: "Nimbahera - (Rajasthan)" },
{ Name: "Nippani - (Karnataka)" },
{ Name: "Nirmal - (Andhra Pradesh)" },
{ Name: "Niwai - (Rajasthan)" },
{ Name: "Niwari - (Madhya Pradesh)" },
{ Name: "Nizamabad - (Andhra Pradesh)" },
{ Name: "Nohar - (Rajasthan)" },
{ Name: "Noida - (Uttar Pradesh)" },
{ Name: "Nokha - (Bihar)" },
{ Name: "Nokha - (Rajasthan)" },
{ Name: "Nongstoin - (Meghalaya)" },
{ Name: "Noorpur - (Uttar Pradesh)" },
{ Name: "North Lakhimpur - (Assam)" },
{ Name: "Nowgong - (Madhya Pradesh)" },
{ Name: "Nowrozabad - (Madhya Pradesh)" },
{ Name: "Nuzvid - (Andhra Pradesh)" },
{ Name: "O' Valley - (Tamil Nadu)" },
{ Name: "Oddanchatram - (Tamil Nadu)" },
{ Name: "Obra - (Uttar Pradesh)" },
{ Name: "Ongole - (Andhra Pradesh)" },
{ Name: "Orai - (Uttar Pradesh)" },
{ Name: "Osmanabad - (Maharashtra)" },
{ Name: "Ottappalam - (Kerala)" },
{ Name: "Ozar - (Maharashtra)" },
{ Name: "P.N.Patti - (Tamil Nadu)" },
{ Name: "Pachora - (Maharashtra)" },
{ Name: "Pachore - (Madhya Pradesh)" },
{ Name: "Pacode - (Tamil Nadu)" },
{ Name: "Padmanabhapuram - (Tamil Nadu)" },
{ Name: "Padra - (Gujarat)" },
{ Name: "Padrauna - (Uttar Pradesh)" },
{ Name: "Paithan - (Maharashtra)" },
{ Name: "Pakaur - (Jharkhand)" },
{ Name: "Palacole - (Andhra Pradesh)" },
{ Name: "Palai - (Kerala)" },
{ Name: "Palakkad - (Kerala)" },
{ Name: "Palani - (Tamil Nadu)" },
{ Name: "Palanpur - (Gujarat)" },
{ Name: "Palasa Kasibugga - (Andhra Pradesh)" },
{ Name: "Palghar - (Maharashtra)" },
{ Name: "Pali - (Rajasthan)" },
{ Name: "Pali - (Madhya Pradesh)" },
{ Name: "Palia Kalan - (Uttar Pradesh)" },
{ Name: "Palitana - (Gujarat)" },
{ Name: "Pondur - (Andhra pradesh)" },
{ Name: "Palladam - (Tamil Nadu)" },
{ Name: "Pallapatti - (Tamil Nadu)" },
{ Name: "Pallikonda - (Tamil Nadu)" },
{ Name: "Palwal - (Haryana)" },
{ Name: "Palwancha - (Andhra Pradesh)" },
{ Name: "Panagar - (Madhya Pradesh)" },
{ Name: "Panagudi - (Tamil Nadu)" },
{ Name: "Panaji - (Goa)" },
{ Name: "Panchkula - (Haryana)" },
{ Name: "Panchla - (West Bengal)" },
{ Name: "Pandharkaoda - (Maharashtra)" },
{ Name: "Pandharpur - (Maharashtra)" },
{ Name: "Pandhurna - (Madhya Pradesh)" },
{ Name: "Pandua - (West Bengal)" },
{ Name: "Panipat - (Haryana)" },
{ Name: "Panna - (Madhya Pradesh)" },
{ Name: "Panniyannur - (Kerala)" },
{ Name: "Panruti - (Tamil Nadu)" },
{ Name: "Panvel - (Maharashtra)" },
{ Name: "Pappinisseri - (Kerala)" },
{ Name: "Paradip - (Orissa)" },
{ Name: "Paramakudi - (Tamil Nadu)" },
{ Name: "Parangipettai - (Tamil Nadu)" },
{ Name: "Parasi - (Uttar Pradesh)" },
{ Name: "Paravoor - (Kerala)" },
{ Name: "Parbhani - (Maharashtra)" },
{ Name: "Pardi - (Gujarat)" },
{ Name: "Parlakhemundi - (Orissa)" },
{ Name: "Parli - (Maharashtra)" },
{ Name: "Parola - (Maharashtra)" },
{ Name: "Partur - (Maharashtra)" },
{ Name: "Parvathipuram - (Andhra Pradesh)" },
{ Name: "Pasan - (Madhya Pradesh)" },
{ Name: "Paschim Punropara - (West Bengal)" },
{ Name: "Pasighat - (Arunachal Pradesh)" },
{ Name: "Patan - (Gujarat)" },
{ Name: "Pathanamthitta - (Kerala)" },
{ Name: "Pathankot - (Punjab)" },
{ Name: "Pathardi - (Maharashtra)" },
{ Name: "Pathri - (Maharashtra)" },
{ Name: "Patiala - (Punjab)" },
{ Name: "Patna - (Bihar)" },
{ Name: "Patran - (Punjab)" },
{ Name: "Patratu - (Jharkhand)" },
{ Name: "Pattamundai - (Orissa)" },
{ Name: "Patti - (Punjab)" },
{ Name: "Pattukkottai - (Tamil Nadu)" },
{ Name: "Patur - (Maharashtra)" },
{ Name: "Pauni - (Maharashtra)" },
{ Name: "Pauri - (Uttarakhand)" },
{ Name: "Paavagada - (Karnataka)" },
{ Name: "Payyannur - (Kerala)" },
{ Name: "Pedana - (Andhra Pradesh)" },
{ Name: "Peddapuram - (Andhra Pradesh)" },
{ Name: "Pehowa - (Haryana)" },
{ Name: "Pen - (Maharashtra)" },
{ Name: "Perambalur - (Tamil Nadu)" },
{ Name: "Peravurani - (Tamil Nadu)" },
{ Name: "Peringathur - (Kerala)" },
{ Name: "Perinthalmanna - (Kerala)" },
{ Name: "Periyakulam - (Tamil Nadu)" },
{ Name: "Periyasemur - (Tamil Nadu)" },
{ Name: "Pernampattu - (Tamil Nadu)" },
{ Name: "Perumbavoor - (Kerala)" },
{ Name: "Petlad - (Gujarat)" },
{ Name: "Phagwara - (Punjab)" },
{ Name: "Phalodi - (Rajasthan)" },
{ Name: "Phaltan - (Maharashtra)" },
{ Name: "Phillaur - (Punjab)" },
{ Name: "Phulabani - (Orissa)" },
{ Name: "Phulera - (Rajasthan)" },
{ Name: "Phulpur - (Uttar Pradesh)" },
{ Name: "Phusro - (Jharkhand)" },
{ Name: "Pihani - (Uttar Pradesh)" },
{ Name: "Pilani - (Rajasthan)" },
{ Name: "Pilibanga - (Rajasthan)" },
{ Name: "Pilibhit - (Uttar Pradesh)" },
{ Name: "Pilkhuwa - (Uttar Pradesh)" },
{ Name: "Pindwara - (Rajasthan)" },
{ Name: "Pinjore - (Haryana)" },
{ Name: "Pipar City - (Rajasthan)" },
{ Name: "Pipariya - (Madhya Pradesh)" },
{ Name: "Piro - (Bihar)" },
{ Name: "Pithampur - (Madhya Pradesh)" },
{ Name: "Pithapuram - (Andhra Pradesh)" },
{ Name: "Pithoragarh - (Uttarakhand)" },
{ Name: "Pollachi - (Tamil Nadu)" },
{ Name: "Polur - (Tamil Nadu)" },
{ Name: "Pondicherry - (Pondicherry)" },
{ Name: "Ponnani - (Kerala)" },
{ Name: "Ponneri - (Tamil Nadu)" },
{ Name: "Ponnur - (Andhra Pradesh)" },
{ Name: "Porbandar - (Gujarat)" },
{ Name: "Porsa - (Madhya Pradesh)" },
{ Name: "Port Blair - (Andaman and Nicobar Islands)" },
{ Name: "Powayan - (Uttar Pradesh)" },
{ Name: "Prantij - (Rajasthan)" },
{ Name: "Pratapgarh - (Rajasthan)" },
{ Name: "Pratapgarh - (Tripura)" },
{ Name: "Prithvipur - (Madhya Pradesh)" },
{ Name: "Proddatur - (Andhra Pradesh)" },
{ Name: "Pudukkottai - (Tamil Nadu)" },
{ Name: "Pudupattinam - (Tamil Nadu)" },
{ Name: "Pukhrayan - (Uttar Pradesh)" },
{ Name: "Pulgaon - (Maharashtra)" },
{ Name: "Puliyankudi - (Tamil Nadu)" },
{ Name: "Punalur - (Kerala)" },
{ Name: "Punch - (Jammu and Kashmir)" },
{ Name: "Pune - (Maharashtra)" },
{ Name: "Punjaipugalur - (Tamil Nadu)" },
{ Name: "Punganur - (Andhra Pradesh)" },
{ Name: "Puranpur - (Uttar Pradesh)" },
{ Name: "Purna - (Maharashtra)" },
{ Name: "Puri - (Orissa)" },
{ Name: "Purnia - (Bihar)" },
{ Name: "Purquazi - (Uttar Pradesh)" },
{ Name: "Purulia - (West Bengal)" },
{ Name: "Purwa - (Uttar Pradesh)" },
{ Name: "Pusad - (Maharashtra)" },
{ Name: "Puthooru - (Karnataka)" },
{ Name: "Puttur - (Andhra Pradesh)" },
{ Name: "Qadian - (Punjab)" },
{ Name: "Quilandy - (Kerala)" },
{ Name: "Rabakavi Banahatti - (Karnataka)" },
{ Name: "Radhanpur - (Gujarat)" },
{ Name: "Rae Bareli - (Uttar Pradesh)" },
{ Name: "Rafiganj - (Bihar)" },
{ Name: "Raghogarh-Vijaypur - (Madhya Pradesh)" },
{ Name: "Raghunathpur - (West Bengal)" },
{ Name: "Rahatgarh - (Madhya Pradesh)" },
{ Name: "Raichuri - (Maharashtra)" },
{ Name: "Raayachuru - (Karnataka)" },
{ Name: "Raiganj - (West Bengal)" },
{ Name: "Raigarh - (Chhattisgarh)" },
{ Name: "Raikot - (Punjab)" },
{ Name: "Raipur - (Chhattisgarh)" },
{ Name: "Rairangpur - (Orissa)" },
{ Name: "Raisen - (Madhya Pradesh)" },
{ Name: "Raisinghnagar - (Rajasthan)" },
{ Name: "Rajagangapur - (Orissa)" },
{ Name: "Rajahmundry - (Andhra Pradesh)" },
{ Name: "Rajakhera - (Rajasthan)" },
{ Name: "Rajaldesar - (Rajasthan)" },
{ Name: "Rajam - (Andhra Pradesh)" },
{ Name: "Rajampet - (Andhra Pradesh)" },
{ Name: "Rajapalayam - (Tamil Nadu)" },
{ Name: "Rajauri - (Jammu and Kashmir)" },
{ Name: "Rajgarh (Alwar) - (Rajasthan)" },
{ Name: "Rajgarh (Churu) - (Rajasthan)" },
{ Name: "Rajgarh - (Madhya Pradesh)" },
{ Name: "Rajgir - (Bihar)" },
{ Name: "Rajkot - (Gujarat)" },
{ Name: "Rajnandgaon - (Chhattisgarh)" },
{ Name: "Rajpipla - (Gujarat)" },
{ Name: "Rajpura - (Punjab)" },
{ Name: "Rajsamand - (Rajasthan)" },
{ Name: "Rajula - (Gujarat)" },
{ Name: "Rajura - (Maharashtra)" },
{ Name: "Ramachandrapuram - (Andhra Pradesh)" },
{ Name: "Ramagundam - (Andhra Pradesh)" },
{ Name: "Raamanagara - (Karnataka)" },
{ Name: "Ramanathapuram - (Tamil Nadu)" },
{ Name: "Raamadurga - (Karnataka)" },
{ Name: "Rameshwaram - (Tamil Nadu)" },
{ Name: "Ramganj Mandi - (Rajasthan)" },
{ Name: "Ramngarh - (Jharkhand)" },
{ Name: "Ramngarh - (Rajasthan)" },
{ Name: "Ramnagar - (Bihar)" },
{ Name: "Ramnagar - (Uttarakhand)" },
{ Name: "Rampur - (Uttar Pradesh)" },
{ Name: "Rampur Maniharan - (Uttar Pradesh)" },
{ Name: "Rampura Phul - (Punjab)" },
{ Name: "Rampurhat - (West Bengal)" },
{ Name: "Ramtek - (Maharashtra)" },
{ Name: "Ranaghat - (West Bengal)" },
{ Name: "Ranavav - (Gujarat)" },
{ Name: "Ranchi - (Jharkhand)" },
{ Name: "Rangia - (Assam)" },
{ Name: "Rania - (Haryana)" },
{ Name: "Ranibennur - (Karnataka)" },
{ Name: "Rapar - (Gujarat)" },
{ Name: "Rasipuram - (Tamil Nadu)" },
{ Name: "Rasra - (Uttar Pradesh)" },
{ Name: "Ratangarh - (Rajasthan)" },
{ Name: "Rath - (Uttar Pradesh)" },
{ Name: "Ratia - (Haryana)" },
{ Name: "Ratlam - (Madhya Pradesh)" },
{ Name: "Ratnagiri - (Maharashtra)" },
{ Name: "Rau - (Madhya Pradesh)" },
{ Name: "Raurkela - (Orissa)" },
{ Name: "Raver - (Maharashtra)" },
{ Name: "Rawatbhata - (Rajasthan)" },
{ Name: "Rawatsar - (Rajasthan)" },
{ Name: "Raxaul Bazar - (Bihar)" },
{ Name: "Rayachoti - (Andhra Pradesh)" },
{ Name: "Rayadurg - (Andhra Pradesh)" },
{ Name: "Rayagada - (Orissa)" },
{ Name: "Reengus - (Rajasthan)" },
{ Name: "Rehli - (Madhya Pradesh)" },
{ Name: "Renigunta - (Andhra Pradesh)" },
{ Name: "Renukoot - (Uttar Pradesh)" },
{ Name: "Reoti - (Uttar Pradesh)" },
{ Name: "Repalle - (Andhra Pradesh)" },
{ Name: "Revelganj - (Bihar)" },
{ Name: "Rewa - (Madhya Pradesh)" },
{ Name: "Rewari - (Haryana)" },
{ Name: "Rishikesh - (Uttarakhand)" },
{ Name: "Risod - (Maharashtra)" },
{ Name: "Robertsganj - (Uttar Pradesh)" },
{ Name: "Robertson Pet - (Karnataka)" },
{ Name: "Rohtak - (Haryana)" },
{ Name: "Ron - (Karnataka)" },
{ Name: "Roorkee - (Uttarakhand)" },
{ Name: "Rosera - (Bihar)" },
{ Name: "Rudauli - (Uttar Pradesh)" },
{ Name: "Rudrapur - (Uttarakhand)" },
{ Name: "Rudrapur - (Uttar Pradesh)" },
{ Name: "Rupnagar - (Punjab)" },
{ Name: "Sabalgarh - (Madhya Pradesh)" },
{ Name: "Sadabad - (Uttar Pradesh)" },
{ Name: "Sadalaga - (Karnataka)" },
{ Name: "Sadasivpet - (Andhra Pradesh)" },
{ Name: "Sadri - (Rajasthan)" },
{ Name: "Sadulshahar - (Rajasthan)" },
{ Name: "Safidon - (Haryana)" },
{ Name: "Safipur - (Uttar Pradesh)" },
{ Name: "Sagar - (Madhya Pradesh)" },
{ Name: "Saagara - (Karnataka)" },
{ Name: "Sagwara - (Rajasthan)" },
{ Name: "Saharanpur - (Uttar Pradesh)" },
{ Name: "Saharsa - (Bihar)" },
{ Name: "Sahaspur - (Uttar Pradesh)" },
{ Name: "Sahaswan - (Uttar Pradesh)" },
{ Name: "Sahawar - (Uttar Pradesh)" },
{ Name: "Sahibganj - (Jharkhand)" },
{ Name: "Sahjanwa - (Uttar Pradesh)" },
{ Name: "Saidpur - (Uttar Pradesh)" },
{ Name: "Saiha - (Mizoram)" },
{ Name: "Sailu - (Maharashtra)" },
{ Name: "Sainthia - (West Bengal)" },
{ Name: "Sakaleshapura - (Karnataka)" },
{ Name: "Sakti - (Chhattisgarh)" },
{ Name: "Salaya - (Gujarat)" },
{ Name: "Salem - (Tamil Nadu)" },
{ Name: "Salur - (Andhra Pradesh)" },
{ Name: "Samalkha - (Haryana)" },
{ Name: "Samalkot - (Andhra Pradesh)" },
{ Name: "Samana - (Punjab)" },
{ Name: "Samastipur - (Bihar)" },
{ Name: "Sambalpur - (Orissa)" },
{ Name: "Sambhal - (Uttar Pradesh)" },
{ Name: "Sambhar - (Rajasthan)" },
{ Name: "Samdhan - (Uttar Pradesh)" },
{ Name: "Samthar - (Uttar Pradesh)" },
{ Name: "Sanand - (Gujarat)" },
{ Name: "Sanawad - (Madhya Pradesh)" },
{ Name: "Sanchore - (Rajasthan)" },
{ Name: "Sandi - (Uttar Pradesh)" },
{ Name: "Sandila - (Uttar Pradesh)" },
{ Name: "Sandur - (Karnataka)" },
{ Name: "Sangamner - (Maharashtra)" },
{ Name: "Sangareddy - (Andhra Pradesh)" },
{ Name: "Sangaria - (Rajasthan)" },
{ Name: "Sangli - (Maharashtra)" },
{ Name: "Sangole - (Maharashtra)" },
{ Name: "Sangrur - (Punjab)" },
{ Name: "Sankarankoil - (Tamil Nadu)" },
{ Name: "Sankari - (Tamil Nadu)" },
{ Name: "Sankeshwara - (Karnataka)" },
{ Name: "Santipur - (West Bengal)" },
{ Name: "Sarangpur - (Madhya Pradesh)" },
{ Name: "Sardarshahar - (Rajasthan)" },
{ Name: "Sardhana - (Uttar Pradesh)" },
{ Name: "Sarni - (Madhya Pradesh)" },
{ Name: "Sasaram - (Bihar)" },
{ Name: "Sasvad - (Maharashtra)" },
{ Name: "Satana - (Maharashtra)" },
{ Name: "Satara - (Maharashtra)" },
{ Name: "Satna - (Madhya Pradesh)" },
{ Name: "Sathyamangalam - (Tamil Nadu)" },
{ Name: "Sattenapalle - (Andhra Pradesh)" },
{ Name: "Sattur - (Tamil Nadu)" },
{ Name: "Saunda - (Jharkhand)" },
{ Name: "Soudaththi-Yellamma - (Karnataka)" },
{ Name: "Sausar - (Madhya Pradesh)" },
{ Name: "Savarkundla - (Gujarat)" },
{ Name: "Savanur - (Karnataka)" },
{ Name: "Savner - (Maharashtra)" },
{ Name: "Sawai Madhopur - (Rajasthan)" },
{ Name: "Sawantwadi - (Maharashtra)" },
{ Name: "Sedam - (Karnataka)" },
{ Name: "Sehore - (Madhya Pradesh)" },
{ Name: "Sendhwa - (Madhya Pradesh)" },
{ Name: "Seohara - (Uttar Pradesh)" },
{ Name: "Seoni - (Madhya Pradesh)" },
{ Name: "Seoni-Malwa - (Madhya Pradesh)" },
{ Name: "Shahabad - (Karnataka)" },
{ Name: "Shahabad, Hardoi - (Uttar Pradesh)" },
{ Name: "Shahabad, Rampur - (Uttar Pradesh)" },
{ Name: "Shahade - (Maharashtra)" },
{ Name: "Shahbad - (Haryana)" },
{ Name: "Shahdol - (Madhya Pradesh)" },
{ Name: "Shahganj - (Uttar Pradesh)" },
{ Name: "Shahjahanpur - (Uttar Pradesh)" },
{ Name: "Shahapura - (Karnataka)" },
{ Name: "Shahpura - (Rajasthan)" },
{ Name: "Shahpura - (Rajasthan)" },
{ Name: "Shajapur - (Madhya Pradesh)" },
{ Name: "Shamgarh - (Madhya Pradesh)" },
{ Name: "Shamli - (Uttar Pradesh)" },
{ Name: "Shamsabad, Agra - (Uttar Pradesh)" },
{ Name: "Shamsabad, Farrukhabad - (Uttar Pradesh)" },
{ Name: "Shegaon - (Maharashtra)" },
{ Name: "Sheikhpura - (Bihar)" },
{ Name: "Shendurjana - (Maharashtra)" },
{ Name: "Shenkottai - (Tamil Nadu)" },
{ Name: "Sheoganj - (Rajasthan)" },
{ Name: "Sheohar - (Bihar)" },
{ Name: "Sheopur - (Madhya Pradesh)" },
{ Name: "Sherghati - (Bihar)" },
{ Name: "Sherkot - (Uttar Pradesh)" },
{ Name: "Shiggaavi - (Karnataka)" },
{ Name: "Shikapur - (Karnataka)" },
{ Name: "Shikarpur, Bulandshahr - (Uttar Pradesh)" },
{ Name: "Shikohabad - (Uttar Pradesh)" },
{ Name: "Shillong - (Meghalaya)" },
{ Name: "Shimla - (Himachal Pradesh)" },
{ Name: "Shivamogga - (Karnataka)" },
{ Name: "Shirdi - (Maharashtra)" },
{ Name: "Shirpur-Warwade - (Maharashtra)" },
{ Name: "Shirur - (Maharashtra)" },
{ Name: "Shishgarh - (Uttar Pradesh)" },
{ Name: "Shivpuri - (Madhya Pradesh)" },
{ Name: "Sholavandan - (Tamil Nadu)" },
{ Name: "Sholingur - (Tamil Nadu)" },
{ Name: "Shoranur - (Kerala)" },
{ Name: "Surapura - (Karnataka)" },
{ Name: "Shrigonda - (Maharashtra)" },
{ Name: "Shrirampur - (Maharashtra)" },
{ Name: "Shree Rangapattana - (Karnataka)" },
{ Name: "Shujalpur - (Madhya Pradesh)" },
{ Name: "Siana - (Uttar Pradesh)" },
{ Name: "Sibsagar - (Assam)" },
{ Name: "Siddipet - (Andhra Pradesh)" },
{ Name: "Sidhi - (Madhya Pradesh)" },
{ Name: "Sidhpur - (Gujarat)" },
{ Name: "Sidhalaghatta - (Karnataka)" },
{ Name: "Sihor - (Gujarat)" },
{ Name: "Sihora - (Madhya Pradesh)" },
{ Name: "Sikanderpur - (Uttar Pradesh)" },
{ Name: "Sikandra Rao - (Uttar Pradesh)" },
{ Name: "Sikandrabad - (Uttar Pradesh)" },
{ Name: "Sikar - (Rajasthan)" },
{ Name: "Silao - (Bihar)" },
{ Name: "Silapathar - (Assam)" },
{ Name: "Silchar - (Assam)" },
{ Name: "Siliguri - (West Bengal)" },
{ Name: "Sillod - (Maharashtra)" },
{ Name: "Silvassa - (Dadra and Nagar Haveli)" },
{ Name: "Simdega - (Jharkhand)" },
{ Name: "Sindhagi - (Karnataka)" },
{ Name: "Sindhanooru - (Karnataka)" },
{ Name: "Singapur - (Andhra Pradesh)" },
{ Name: "Singrauli - (Madhya Pradesh)" },
{ Name: "Sinnar - (Maharashtra)" },
{ Name: "Sira - (Karnataka)" },
{ Name: "Sircilla - (Andhra Pradesh)" },
{ Name: "Sirhind Fatehgarh Sahib - (Punjab)" },
{ Name: "Sirkali - (Tamil Nadu)" },
{ Name: "Sirohi - (Rajasthan)" },
{ Name: "Sironj - (Madhya Pradesh)" },
{ Name: "Sirsa - (Haryana)" },
{ Name: "Sirsaganj - (Uttar Pradesh)" },
{ Name: "Sirsi - (Karnataka)" },
{ Name: "Sirsi - (Uttar Pradesh)" },
{ Name: "Sheraguppa - (Karnataka)" },
{ Name: "Sitamarhi - (Bihar)" },
{ Name: "Sitapur - (Uttar Pradesh)" },
{ Name: "Sitarganj - (Uttarakhand)" },
{ Name: "Sivaganga - (Tamil Nadu)" },
{ Name: "Sivagiri - (Tamil Nadu)" },
{ Name: "Sivakasi - (Tamil Nadu)" },
{ Name: "Siwan - (Bihar)" },
{ Name: "Sohagpur - (Madhya Pradesh)" },
{ Name: "Sohna - (Haryana)" },
{ Name: "Sojat - (Rajasthan)" },
{ Name: "Solan - (Himachal Pradesh)" },
{ Name: "Solapur - (Maharashtra)" },
{ Name: "Sonamukhi - (West Bengal)" },
{ Name: "Sonepur - (Bihar)" },
{ Name: "Songadh - (Gujarat)" },
{ Name: "Sonipat - (Haryana)" },
{ Name: "Sopore - (Jammu and Kashmir)" },
{ Name: "Soro - (Orissa)" },
{ Name: "Soron - (Uttar Pradesh)" },
{ Name: "Soyagaon - (Maharashtra)" },
{ Name: "Sri Madhopur - (Rajasthan)" },
{ Name: "Srikakulam - (Andhra Pradesh)" },
{ Name: "Srikalahasti - (Andhra Pradesh)" },
{ Name: "Srinagar - (Jammu and Kashmir)" },
{ Name: "Shreenivaasapura - (Karnataka)" },
{ Name: "Srisailam Project (Right Flank Colony) Township - (Andhra Pradesh)" },
{ Name: "Srirampore - (West Bengal)" },
{ Name: "Srivilliputhur - (Tamil Nadu)" },
{ Name: "Suar - (Uttar Pradesh)" },
{ Name: "Sugauli - (Bihar)" },
{ Name: "Sujangarh - (Rajasthan)" },
{ Name: "Sujanpur - (Punjab)" },
{ Name: "Sultanganj - (Bihar)" },
{ Name: "Sultanpur - (Uttar Pradesh)" },
{ Name: "Sumerpur - (Rajasthan)" },
{ Name: "Sumerpur - (Uttar Pradesh)" },
{ Name: "Sunabeda - (Orissa)" },
{ Name: "Sunam - (Punjab)" },
{ Name: "Sundargarh - (Orissa)" },
{ Name: "Sundarnagar - (Himachal Pradesh)" },
{ Name: "Supaul - (Bihar)" },
{ Name: "Surandai - (Tamil Nadu)" },
{ Name: "Surat - (Gujarat)" },
{ Name: "Suratgarh - (Rajasthan)" },
{ Name: "Suri - (West Bengal)" },
{ Name: "Suriyampalayam - (Tamil Nadu)" },
{ Name: "Suryapet - (Andhra Pradesh)" },
{ Name: "Tadepalligudem - (Andhra Pradesh)" },
{ Name: "Tadpatri - (Andhra Pradesh)" },
{ Name: "Taki - (West Bengal)" },
{ Name: "Talaja - (Gujarat)" },
{ Name: "Talcher - (Orissa)" },
{ Name: "Talegaon Dabhade - (Maharashtra)" },
{ Name: "Thaalikote - (Karnataka)" },
{ Name: "Taliparamba - (Kerala)" },
{ Name: "Talode - (Maharashtra)" },
{ Name: "Talwara - (Punjab)" },
{ Name: "Tamluk - (West Bengal)" },
{ Name: "Tanda - (Uttar Pradesh)" },
{ Name: "Tanda - (Uttar Pradesh)" },
{ Name: "Tandur - (Andhra Pradesh)" },
{ Name: "Tanuku - (Andhra Pradesh)" },
{ Name: "Tarakeswar - (West Bengal)" },
{ Name: "Tarana - (Madhya Pradesh)" },
{ Name: "Taranagar - (Rajasthan)" },
{ Name: "Taraori - (Haryana)" },
{ Name: "Tarikere - (Karnataka)" },
{ Name: "Tarn Taran - (Punjab)" },
{ Name: "Tasgaon - (Maharashtra)" },
{ Name: "Tehri - (Uttarakhand)" },
{ Name: "Tekkalakote - (Karnataka)" },
{ Name: "Tenali - (Andhra Pradesh)" },
{ Name: "Tenkasi - (Tamil Nadu)" },
{ Name: "Tenu Dam-cum- Kathhara - (Jharkhand)" },
{ Name: "Thergallu - (Karnataka)" },
{ Name: "Tetri Bazar - (Uttar Pradesh)" },
{ Name: "Tezpur - (Assam)" },
{ Name: "Thakurdwara - (Uttar Pradesh)" },
{ Name: "Thammampatti - (Tamil Nadu)" },
{ Name: "Thana Bhawan - (Uttar Pradesh)" },
{ Name: "Thanesar - (Haryana)" },
{ Name: "Thangadh - (Gujarat)" },
{ Name: "Thanjavur - (Tamil Nadu)" },
{ Name: "Tharad - (Gujarat)" },
{ Name: "Tharamangalam - (Tamil Nadu)" },
{ Name: "Tharangambadi - (Tamil Nadu)" },
{ Name: "Theni Allinagaram - (Tamil Nadu)" },
{ Name: "Thirumangalam - (Tamil Nadu)" },
{ Name: "Thirunindravur - (Tamil Nadu)" },
{ Name: "Thiruparappu - (Tamil Nadu)" },
{ Name: "Thirupuvanam - (Tamil Nadu)" },
{ Name: "Thiruthuraipoondi - (Tamil Nadu)" },
{ Name: "Thiruvalla - (Kerala)" },
{ Name: "Thiruvallur - (Tamil Nadu)" },
{ Name: "Thiruvananthapuram - (Kerala)" },
{ Name: "Thiruvarur - (Tamil Nadu)" },
{ Name: "Thodupuzha - (Kerala)" },
{ Name: "Thoothukudi - (Tamil Nadu)" },
{ Name: "Thoubal - (Manipur)" },
{ Name: "Thrissur - (Kerala)" },
{ Name: "Thuraiyur - (Tamil Nadu)" },
{ Name: "Tikamgarh - (Madhya Pradesh)" },
{ Name: "Tilda Newra - (Chhattisgarh)" },
{ Name: "Tilhar - (Uttar Pradesh)" },
{ Name: "Tindivanam - (Tamil Nadu)" },
{ Name: "Tinsukia - (Assam)" },
{ Name: "Thipatooru - (Karnataka)" },
{ Name: "Tirora - (Maharashtra)" },
{ Name: "Tiruchendur - (Tamil Nadu)" },
{ Name: "Tiruchengode - (Tamil Nadu)" },
{ Name: "Tiruchirappalli - (Tamil Nadu)" },
{ Name: "Tirukalukundram - (Tamil Nadu)" },
{ Name: "Tirukkoyilur - (Tamil Nadu)" },
{ Name: "Tirunelveli - (Tamil Nadu)" },
{ Name: "Tirupathur - (Tamil Nadu)" },
{ Name: "Tirupathur - (Tamil Nadu)" },
{ Name: "Tirupati - (Andhra Pradesh)" },
{ Name: "Tiruppur - (Tamil Nadu)" },
{ Name: "Tirur - (Kerala)" },
{ Name: "Tiruttani - (Tamil Nadu)" },
{ Name: "Tiruvannamalai - (Tamil Nadu)" },
{ Name: "Tiruvethipuram - (Tamil Nadu)" },
{ Name: "Tiruvuru - (Andhra Pradesh)" },
{ Name: "Tirwaganj - (Uttar Pradesh)" },
{ Name: "Titlagarh - (Orissa)" },
{ Name: "Tittakudi - (Tamil Nadu)" },
{ Name: "Todabhim - (Rajasthan)" },
{ Name: "Todaraisingh - (Rajasthan)" },
{ Name: "Tohana - (Haryana)" },
{ Name: "Tonk - (Rajasthan)" },
{ Name: "Tuensang - (Nagaland)" },
{ Name: "Tuljapur - (Maharashtra)" },
{ Name: "Tulsipur - (Uttar Pradesh)" },
{ Name: "Thumakooru - (Karnataka)" },
{ Name: "Tumsar - (Maharashtra)" },
{ Name: "Tundla - (Uttar Pradesh)" },
{ Name: "Tuni - (Andhra Pradesh)" },
{ Name: "Tura - (Meghalaya)" },
{ Name: "Uchgaon - (Maharashtra)" },
{ Name: "Udaipur - (Rajasthan)" },
{ Name: "Udaipur - (Tripura)" },
{ Name: "Udaipurwati - (Rajasthan)" },
{ Name: "Udgir - (Maharashtra)" },
{ Name: "Udhagamandalam - (Tamil Nadu)" },
{ Name: "Udhampur - (Jammu and Kashmir)" },
{ Name: "Udumalaipettai - (Tamil Nadu)" },
{ Name: "Udupi - (Karnataka)" },
{ Name: "Ujhani - (Madhya Pradesh)" },
{ Name: "Ujjain - (Madhya Pradesh)" },
{ Name: "Umarga - (Maharashtra)" },
{ Name: "Umaria - (Madhya Pradesh)" },
{ Name: "Umarkhed - (Maharashtra)" },
{ Name: "Umarkote - (Orissa)" },
{ Name: "Umbergaon - (Gujarat)" },
{ Name: "Umred - (Maharashtra)" },
{ Name: "Umreth - (Gujarat)" },
{ Name: "Una - (Gujarat)" },
{ Name: "Unjha - (Gujarat)" },
{ Name: "Unnamalaikadai - (Tamil Nadu)" },
{ Name: "Unnao - (Uttar Pradesh)" },
{ Name: "Upleta - (Gujarat)" },
{ Name: "Uran - (Maharashtra)" },
{ Name: "Uran Islampur - (Maharashtra)" },
{ Name: "Uravakonda - (Andhra Pradesh)" },
{ Name: "Urmar Tanda - (Punjab)" },
{ Name: "Usilampatti - (Tamil Nadu)" },
{ Name: "Uthamapalayam - (Tamil Nadu)" },
{ Name: "Uthiramerur - (Tamil Nadu)" },
{ Name: "Utraula - (Uttar Pradesh)" },
{ Name: "Vadakara - (Kerala)" },
{ Name: "Vadakkuvalliyur - (Tamil Nadu)" },
{ Name: "Vadalur - (Tamil Nadu)" },
{ Name: "Vadgaon Kasba - (Maharashtra)" },
{ Name: "Vadipatti - (Tamil Nadu)" },
{ Name: "Vadnagar - (Gujarat)" },
{ Name: "Vadodara - (Gujarat)" },
{ Name: "Vaijapur - (Maharashtra)" },
{ Name: "Vaikom - (Kerala)" },
{ Name: "Valparai - (Tamil Nadu)" },
{ Name: "Valsad - (Gujarat)" },
{ Name: "Vandavasi - (Tamil Nadu)" },
{ Name: "Vaniyambadi - (Tamil Nadu)" },
{ Name: "Vapi - (Gujarat)" },
{ Name: "Vapi - (Gujarat)" },
{ Name: "Varanasi - (Uttar Pradesh)" },
{ Name: "Varkala - (Kerala)" },
{ Name: "Vasai - (Maharashtra)" },
{ Name: "Vedaranyam - (Tamil Nadu)" },
{ Name: "Vellakoil - (Tamil Nadu)" },
{ Name: "Vellore - (Tamil Nadu)" },
{ Name: "Venkatagiri - (Andhra Pradesh)" },
{ Name: "Veraval - (Gujarat)" },
{ Name: "Vicarabad - (Andhra Pradesh)" },
{ Name: "Vidisha - (Madhya Pradesh)" },
{ Name: "Vijainagar - (Rajasthan)" },
{ Name: "Vijapur - (Gujarat)" },
{ Name: "Vijayapura - (Karnataka)" },
{ Name: "Vijayawada - (Andhra Pradesh)" },
{ Name: "Vikramasingapuram - (Tamil Nadu)" },
{ Name: "Viluppuram - (Tamil Nadu)" },
{ Name: "Vinukonda - (Andhra Pradesh)" },
{ Name: "Viramgam - (Gujarat)" },
{ Name: "Virar - (Maharashtra)" },
{ Name: "Virudhachalam - (Tamil Nadu)" },
{ Name: "Virudhunagar - (Tamil Nadu)" },
{ Name: "Visakhapatnam - (Andhra Pradesh)" },
{ Name: "Visnagar - (Gujarat)" },
{ Name: "Viswanatham - (Tamil Nadu)" },
{ Name: "Vita - (Maharashtra)" },
{ Name: "Vizianagaram - (Andhra Pradesh)" },
{ Name: "Vrindavan - (Uttar Pradesh)" },
{ Name: "Vyara - (Gujarat)" },
{ Name: "Wadgaon Road - (Maharashtra)" },
{ Name: "Wadhwan - (Gujarat)" },
{ Name: "Wadi - (Karnataka)" },
{ Name: "Wai - (Maharashtra)" },
{ Name: "Wanaparthy - (Andhra Pradesh)" },
{ Name: "Wani - (Maharashtra)" },
{ Name: "Wankaner - (Gujarat)" },
{ Name: "Wara Seoni - (Madhya Pradesh)" },
{ Name: "Warangal - (Andhra Pradesh)" },
{ Name: "Wardha - (Maharashtra)" },
{ Name: "Warhapur - (Uttar Pradesh)" },
{ Name: "Warisaliganj - (Bihar)" },
{ Name: "Warora - (Maharashtra)" },
{ Name: "Warud - (Maharashtra)" },
{ Name: "Washim - (Maharashtra)" },
{ Name: "Wokha - (Nagaland)" },
{ Name: "Yaadhagiri - (Karnataka)" },
{ Name: "Yamunanagar - (Haryana)" },
{ Name: "Yanam - (Pondicherry)" },
{ Name: "Yavatmal - (Maharashtra)" },
{ Name: "Yawal - (Maharashtra)" },
{ Name: "Yellandu - (Andhra Pradesh)" },
{ Name: "Yemmiganur - (Andhra Pradesh)" },
{ Name: "Yerraguntla - (Andhra Pradesh)" },
{ Name: "Yevla - (Maharashtra)" },
{ Name: "Zahirabad - (Andhra Pradesh)" },
{ Name: "Zaidpur - (Uttar Pradesh)" },
{ Name: "Zamania - (Uttar Pradesh)" },
{ Name: "Zira - (Punjab)" },
{ Name: "Zirakpur - (Punjab)" },
{ Name: "Zunheboto - (Nagaland)" }
    ];


    if (decisionfactory.getcity()) {
        $scope.selectedCountries = decisionfactory.getcity();
    }


    $scope.increment = function () {

        if ($scope.selectedCountries) {
            $scope.$parent.counter = $scope.$parent.counter + 1;

            $scope.$parent.dynamic = $scope.$parent.counter / $scope.$parent.max * 100;

            $scope.$parent.type = 'warning';

            decisionfactory.setcity($scope.selectedCountries);

            $scope.cityerror = '';

            $state.go('hospitals');
        }
        else {
            $scope.cityerror = 'Enter City';
        }
    }

    $scope.decrement = function () {

        $scope.$parent.counter = $scope.$parent.counter - 1;

        $scope.$parent.dynamic = $scope.$parent.counter / $scope.max * 100;

        $scope.$parent.type = 'warning';

        decisionfactory.setcity(false);

        $state.go('Monthlyexpense');
    }

}]);



